### PR TITLE
Ported to Python3

### PR DESCRIPTION
**Pull request by Samvith96**
Changed some tabs to spaces
Changed file() function to open
Changed r"" regex strings to b"" bytes regex strings
Changed print commands to print functions

### CODE REVIEW

**Comment by volkertb** [comment]
Hi! Thanks for the PR.

However, with your changes, the `test/test-dasm3.sh` script fails.

Even running just the following step from that shellscript directly from a Bash prompt fails:

```
cd test # If you're not in the `test` subfolder yet
PYTHONPATH=.. python3 test.py DOSBOX/RANDOM.COM 076B:0100
```

Running it with Python 2 (even with your Python 3 specific fixes) still works:

```
cd test # If you're not in the `test` subfolder yet
PYTHONPATH=.. python2 test.py DOSBOX/RANDOM.COM 076B:0100
```

The cool thing about the existing test is that you can verify that your changes don't cause any different behavior.

I also had to replace `file` with `open` in `test.py`, but it's still failing in Python 3 with issues in `dasm3.py`, specifically `ord()` expecting string but getting int.

Perhaps you could try getting your changes to work with the existing test(s) before I merge this?

Thanks again! :slightly_smiling_face:

**Comment by Samvith96** [comment]
Hi Volkert,
  I am sorry I raised a pull request without testing. I did not see the
test directory. I will make the necessary patch and update the request.
  Thank you very much for supporting me.
  Regards

**Comment by volkertb** [comment]
No apologies necessary! And thank **you** for contributing to this project. :slightly_smiling_face:

**Comment by Samvith96** [comment]
Hi Volkert,
   I think some mess happened with my git actions. i just needed to add some commits to my forked repo. I rebased and force pushed it. Perhaps that closed my pull request.
```
To github.com:Samvith96/dasm3.git
 + 0159e16...f6e2aed main -> main (forced update)
.
.
.
To github.com:Samvith96/dasm3.git
   f6e2aed..5a47cef  main -> main
```
 Also it looks like the initial commit of the upstream repo has changed. A new commit named " initial directory structure" appears to be added as root commit. Could you please help me with this? Could you merge "5a47cef" from my repo to yours?
Thanks

**Comment by volkertb** [comment]
Hi @Samvith96,

For some reason, your branch seemed to have replaced all the historic commit dates. For that reason, I didn't want to risk merging anything from your branch, so I decided to cherry-pick your commits instead.

So to be safe, I created a new branch from `main` and cherry-picked your commits into it, after which I created a Pull Request for that branch.

I also invited you to the project as a collaborator. If you accept, I'll be able to add you as a reviewer, and you'll be able to review and approve pull requests yourself as well.

See the new Pull Request at https://github.com/volkertb/dasm3/pull/2

**Pull request closed without merging**
